package com.turntable.barcodescanner

import android.content.Context
import androidx.core.content.edit
import org.json.JSONArray
import org.json.JSONObject

/**
 * Serializes app preference XML files to a single JSON document for user-driven backup
 * (e.g. save to Downloads or cloud via SAF).
 */
object SettingsBackup {

    const val SCHEMA_VERSION = 1
    const val ROOT_KEY = "turntableSettingsBackup"

    /** Preference file names included in export (search_prefs holds SearchPrefs + history JSON). */
    private val STORES = listOf(
        SearchPrefs.PREFS_NAME,
        UpdatePrefs.PREFS_NAME,
    )

    fun buildJson(context: Context): JSONObject {
        val root = JSONObject()
        root.put(ROOT_KEY, SCHEMA_VERSION)
        root.put("exportedAtMs", System.currentTimeMillis())
        root.put("packageName", context.packageName)
        val stores = JSONObject()
        for (name in STORES) {
            stores.put(name, preferenceFileToJson(context, name))
        }
        root.put("preferenceStores", stores)
        return root
    }

    /**
     * Restores known preference stores from a JSON backup generated by [buildJson].
     * Existing keys in those stores are cleared first so removed settings are also removed.
     */
    fun restoreFromJson(context: Context, root: JSONObject) {
        val version = root.optInt(ROOT_KEY, -1)
        require(version == SCHEMA_VERSION) {
            "Unsupported backup version: $version"
        }
        val storesObj = root.optJSONObject("preferenceStores")
            ?: error("Missing preferenceStores object")
        for (store in STORES) {
            val storeObj = storesObj.optJSONObject(store) ?: JSONObject()
            restorePreferenceStore(context, store, storeObj)
        }
    }

    private fun preferenceFileToJson(context: Context, prefsName: String): JSONObject {
        val p = context.getSharedPreferences(prefsName, Context.MODE_PRIVATE)
        val o = JSONObject()
        for ((key, value) in p.all.entries.sortedBy { it.key }) {
            when (value) {
                null -> o.put(key, JSONObject.NULL)
                is Boolean -> o.put(key, value)
                is Int -> o.put(key, value)
                is Long -> o.put(key, value)
                is Float -> o.put(key, value.toDouble())
                is String -> o.put(key, value)
                is Set<*> -> {
                    val arr = JSONArray()
                    value.filterIsInstance<String>().sorted().forEach { arr.put(it) }
                    o.put(key, arr)
                }
                else -> o.put(key, value.toString())
            }
        }
        return o
    }

    private fun restorePreferenceStore(context: Context, prefsName: String, json: JSONObject) {
        val prefs = context.getSharedPreferences(prefsName, Context.MODE_PRIVATE)
        prefs.edit {
            clear()
            val keys = json.keys()
            while (keys.hasNext()) {
                val key = keys.next()
                when (val value = json.opt(key)) {
                    null, JSONObject.NULL -> remove(key)
                    is Boolean -> putBoolean(key, value)
                    is Int -> putInt(key, value)
                    is Long -> putLong(key, value)
                    is Double -> {
                        // Float values are serialized as JSON numbers (Double).
                        val asLong = value.toLong()
                        if (value == asLong.toDouble()) putLong(key, asLong)
                        else putFloat(key, value.toFloat())
                    }
                    is String -> putString(key, value)
                    is JSONArray -> {
                        val set = linkedSetOf<String>()
                        for (i in 0 until value.length()) {
                            val entry = value.optString(i, "")
                            if (entry.isNotEmpty()) set.add(entry)
                        }
                        putStringSet(key, set)
                    }
                    else -> putString(key, value.toString())
                }
            }
        }
    }
}
